# Generated by Django 3.2.7 on 2021-10-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pleer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pleer.playlist'),
        ),
    ]
