# Generated by Django 3.2.8 on 2021-10-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleer', '0002_alter_composition_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='audio',
            field=models.FileField(null=True, upload_to='audios'),
        ),
        migrations.AddField(
            model_name='composition',
            name='cover',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
