# Generated by Django 3.2.9 on 2021-11-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pleer', '0003_auto_20211029_1643'),
        ('playlist', '0002_auto_20211107_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('playlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleer.playlist')),
            ],
            bases=('pleer.playlist',),
        ),
    ]
